### ISSUE TITLE
Change the colour of social icons in footer section.

### ISSUE THREAD

**Issue by rwiteshbera** [DevOps-Malayalam/DevOps-Community#15]
The social icons are not properly visible in the footer. I want to add make some customisation so that it looks good.

**Comment by rwiteshbera** [comment]
@AlexyPulivelil  Can you please assign me this issue? I am participating in Hacktoberfest.

**Comment by AlexyPulivelil** [comment]
Feel free to make changes. If possible share a pic here so that I can know how will the footer looks after your edit. Thanks

**Comment by MidouWebDev** [comment]
@AlexyPulivelil can you assign me ?

**Comment by AlexyPulivelil** [comment]
@MidouWebDev The colour change have been done and its successfully merged. You can check for any other suggestions. Thanks

**Comment by enoxSutrisno** [comment]
thanks
