### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by SriSatyaT** [DevOps-Malayalam/DevOps-Community#16]
Hello there, it would be nice if the repo contains discussion opt. if the contributors can ask there they can discuss there and also add hacktoberfest tags to the opened issues.

**Comment by AlexyPulivelil** [comment]
hey, I think in the issue section you can create **hacktoberfest** label is it ?. And the isuues section is open for all and when a particular PR is merged we can close the issues right ?
 But if I'm in the wrong direction feel free to correct me

**Comment by SriSatyaT** [comment]
> hey, I think in the issue section you can create **hacktoberfest** label is it ?. And the isuues section is open for all and when a particular PR is merged we can close the issues right ? But if I'm in the wrong direction feel free to correct me

Hmm Actually the maintainers of the project can add **Hacktoberfest** tag. If you are the maintainer then create new label. Yes when a issue is fixed through the pr you can just close it.

**Comment by AlexyPulivelil** [comment]
Ok, I will add the new label. Thanks for pointing out
