### ISSUE TITLE
Remove scroll bar track while preloader animation

### ISSUE THREAD

**Issue by ri-tae-ka** [DevOps-Malayalam/DevOps-Community#20]
![Screenshot 2021-10-02 153220](https://user-images.githubusercontent.com/79984800/135711671-bb0cc820-a33d-42cb-8e57-1112d05c9a3a.jpg)
Can I work on this issue under hacktoberfest?

**Comment by AlexyPulivelil** [comment]
Can you make it some more precise like how are you going to make the corrections. or how will it look like after the correction ?.

**Comment by AlexyPulivelil** [comment]
You can work on it. I guess after you make the changes, there will not be scroll bar when the site loads.
