### ISSUE TITLE
Increase the size of social media icons

### ISSUE THREAD

**Issue by PalakJain9** [DevOps-Malayalam/DevOps-Community#21]
He, I'd like to increase the size of social media icons. They seem small relatively to the text and circle around them.
Kindly assign me this issue :)

**Comment by AlexyPulivelil** [comment]
@PalakJain9 The size in the frontpage is perfect. If are suggesting edits on other pages, please try to keep it similar to the main page i.e _index.html_ Thanks

**Comment by PalakJain9** [comment]
Hey, if that's so, then I believe social media icons don't need a change. 
Thanks!

**Comment by TishaJhabak1014** [comment]
@AlexyPulivelil Can I improve the section `upcoming events` in the app? Do let me know.

**Comment by AlexyPulivelil** [comment]
@TishaJhabak1014 Hey, I am closing this issue. You can work on upcoming events section. Please create another issue. Thanks 👍
