### ISSUE TITLE
Increase the about page's bg image height and scrollbar colour change

### ISSUE THREAD

**Issue by SayantaniDeb** [DevOps-Malayalam/DevOps-Community#3]
https://user-images.githubusercontent.com/74983536/135621804-2636fb6f-dcf4-41f1-9aea-610b1bc7b6fd.mp4

These are the changes i want to propose. If you have something else on mind please suggest.
Please assign this task to me.

**Comment by AlexyPulivelil** [comment]
Thanks for pointing out the issues. You can work on it and make the necessary corrections
