### ISSUE TITLE
Footer looks a bit distored

### ISSUE THREAD

**Issue by Tishasoumya-02** [DevOps-Malayalam/DevOps-Community#30]
Can i work on the footer part.

**Comment by AlexyPulivelil** [comment]
We would love to see the changes. Thanks

**Comment by Shiyasmohd** [comment]
can u assign me to do this?

**Comment by AlexyPulivelil** [comment]
@Tishasoumya-02 Can give an update. 
@Shiyasmohd As of now I'm unable to give an answer. Will update you soon. 

Thanks

**Comment by Tishasoumya-02** [comment]
Yes I have made the changes ...sorry I forgot to close the issue @Shiyasmohd

**Comment by AlexyPulivelil** [comment]
@Tishasoumya-02 Thanks a lot for the update
@Shiyasmohd I'm really sorry. You can check for another issues and update here. I will look into it.
Thanks
