### ISSUE TITLE
Overlapping in mobile view

### ISSUE THREAD

**Issue by ishikajn8126** [DevOps-Malayalam/DevOps-Community#31]
![DevOps Malayalam - Google Chrome 03-10-2021 12_29_09 (2)](https://user-images.githubusercontent.com/72145053/135743739-8c03c22f-7aef-4360-8c5d-b3932a00a368.jpg)
 Plz assign this issue to me

**Comment by AlexyPulivelil** [comment]
Feel free to make changes. Thanks
