### ISSUE TITLE
Issues with the responsiveness of Page

### ISSUE THREAD

**Issue by AnmolVirdi** [DevOps-Malayalam/DevOps-Community#35]
- The main logo that depicts DevOps flow (Shape of Infinity) creates obstruction in reading the text when the responsiveness of page was tested.
- Also, There are some issues with the footer as we check the responsiveness of the page.
- ![1](https://user-images.githubusercontent.com/67299745/135775906-dd9ce486-1213-41eb-a54b-a7f0d29bb0c0.png)
- ![2](https://user-images.githubusercontent.com/67299745/135775929-c4df0c0d-5366-4498-9ecb-9cee8c11f8a4.png)

**Comment by AlexyPulivelil** [comment]
Thanks for pointing out the issues. So how will you be rectifying the above mentioned issues. Can you share a pic on how does the site looks after the changes.

**Comment by AnmolVirdi** [comment]
I've gone through the project files and realized that the the image with the pinkish background and the DevOps logo is actually a single picture. So to rectify this, I'll separate both these images using photoshop and position the DevOps logo using appropriate styling.  (Although It would be if you can share the sources/designer responsible for the background image. It'll be easier to get those two distinct images then.)
The footer needs styling too.

**Comment by AnmolVirdi** [comment]
Meanwhile, I'll try what all I can do and will share a pic.

**Comment by AlexyPulivelil** [comment]
@AnmolVirdi I guess all the images are available in the images folder. Can you have a look

**Comment by AnmolVirdi** [comment]
@AlexyPulivelil Yes, Actually that's one single picture.
I have 2 solutions: 
1. If a designer created this bg11 image, let's just contact him/her to provide these are 2 separate images(Bg and the DevOps logo)
2. I can alter the text alignment as well as the bg image properties that might rectify the issue. (experimental).
- ![bg11](https://user-images.githubusercontent.com/67299745/135899004-b0a499b6-935a-4efa-b493-22c3e1f70359.jpg)

**Comment by AlexyPulivelil** [comment]
@AnmolVirdi Thanks for suggesting the soluions. Let me see how can I help you on this isssue.
