### ISSUE TITLE
Expert Session

### ISSUE THREAD

**Issue by arpit282** [DevOps-Malayalam/DevOps-Community#36]
I want to work on the Expert session, would you please allow me ?

**Comment by AlexyPulivelil** [comment]
@arpit282 Go ahead, you can work on it. We would love to see your suggestions

**Comment by Sonukumarkeshri4** [comment]
I have made some changes in Expert session, would you please review my PR .

**Comment by AlexyPulivelil** [comment]
@Sonukumarkeshri4 Please check the reply I have given to the PR. Thanks

**Comment by Sonukumarkeshri4** [comment]
Yes , I'm working on it

**Comment by Sonukumarkeshri4** [comment]
Can you please verify the PR, I have done the changes, aligned icons, and structured the document a bit.  #47 
Thank You

**Comment by AlexyPulivelil** [comment]
@Sonukumarkeshri4 Its little bit confusing having issue and PR differently. So i' closing this one. You can check the PR section. 
#44 
Thanks
