### ISSUE TITLE
Style facebook button 

### ISSUE THREAD

**Issue by Evavic44** [DevOps-Malayalam/DevOps-Community#37]
The facebook button doesn't have the same styling as other buttons.
Permission to fix this?

![devops_repo](https://user-images.githubusercontent.com/62628408/135887240-ffe725f4-ea30-4517-9c36-9aeea4736303.png)

**Comment by AlexyPulivelil** [comment]
Fell free to make changes. Also do check other pages also to make sure everything looks same. Thanks

**Comment by Shreyalytical** [comment]
Can I work on this ?

**Comment by Evavic44** [comment]
> Feel free to make changes. Also do check other pages also to make sure everything looks same. Thanks

Fixed!? 🤔

**Comment by Omkar845** [comment]
Can I work on this issue

**Comment by Harsh-bartariya** [comment]
Can i work on this.. Issue.. 
Plz assign it to me
