### ISSUE TITLE
Overlapping issue

### ISSUE THREAD

**Issue by JahnaviKashyap19** [DevOps-Malayalam/DevOps-Community#39]
![Screenshot (527)](https://user-images.githubusercontent.com/57027274/135901003-14f151b1-c46a-48d4-8d81-94fd16db3cde.png)
I want to fix the overlapping cross symbol.

**Comment by shazm12** [comment]
hi can I take up this issue @JahnaviKashyap19 ?

**Comment by JahnaviKashyap19** [comment]
> hi can I take up this issue @JahnaviKashyap19 ?

Hey @shazm12 I opened the issue so that I can work on it. You can create some other issue.

**Comment by shazm12** [comment]
Thank you for the opportunity

**Comment by AlexyPulivelil** [comment]
@JahnaviKashyap19 Feel free to make changes. Thanks.

**Comment by AlexyPulivelil** [comment]
@JahnaviKashyap19 I guess this particular changes are only available in the mobile view right.

**Comment by JahnaviKashyap19** [comment]
> @JahnaviKashyap19 I guess this particular changes are only available in the mobile view right.

no this is in laptop view.

**Comment by AlexyPulivelil** [comment]
No way, May be you have forked few days before. Currently its avaliable in mobile view only. And to your question, you can work on it. Thanks

**Comment by shazm12** [comment]
hi @JahnaviKashyap19  can u tell me where and how does this overlapping issue comes up cause I am not getting it anywhere on website?

**Comment by AlexyPulivelil** [comment]
@JahnaviKashyap19 Thanks. So I'm closing this issue
