### ISSUE TITLE
Resize the logo

### ISSUE THREAD

**Issue by vikkastiwari** [DevOps-Malayalam/DevOps-Community#43]
I want to make the size of the logo even in the sticky and nonsticky phase.
I will resize the logo and update the same.
I want to take up this issue, Please assign this to me.
Thank You

**Comment by AlexyPulivelil** [comment]
@vikkastiwari Sorry, I couldn't get you correctly. Resize in what sense ? Can you share a pic of how will it look after you make changes. 
Thanks.

**Comment by vikkastiwari** [comment]
Okay I will share it with you

**Comment by vikkastiwari** [comment]
previously the size of the white logo was 120px X120px and the other was 150px X 80px

I resized both of them to 80px X 80px to look even when we scroll.

![1](https://user-images.githubusercontent.com/51874681/136021212-bd53ce7f-fe0e-4787-8e6f-5d169422da18.PNG)
![2](https://user-images.githubusercontent.com/51874681/136021285-15292c5f-f908-48dc-97b3-d34de0519cf9.PNG)

**Comment by AlexyPulivelil** [comment]
Thanks a lot.

**Comment by vikkastiwari** [comment]
Welcome :)
