### ISSUE TITLE
Alignment of icons

### ISSUE THREAD

**Issue by shreyamedehal** [DevOps-Malayalam/DevOps-Community#46]
Align the social media icons horizontally in the "About us" and "Events'' page
#### before
![icons before](https://user-images.githubusercontent.com/82696347/136014034-6a84fc75-7a8a-48a7-a6e8-a05a9731005c.png)
#### after
![icons after](https://user-images.githubusercontent.com/82696347/136014519-7fdd7f92-4bbc-4956-8819-ffa6316e942e.png)

**Comment by AlexyPulivelil** [comment]
@shreyamedehal Cool. Looks awesome, you can work on it. 
Thanks

**Comment by AlexyPulivelil** [comment]
@shreyamedehal That suggestion was made by someone else and its already Pulled to the repo. You can check for the other issues. THANKS.

**Comment by shreyamedehal** [comment]
Alright! Can I fix the icons in the Hamburger Menu?

![icons](https://user-images.githubusercontent.com/82696347/136026798-19ec0e5c-df22-4089-9c13-125f6aa2b3ad.png)

**Comment by AlexyPulivelil** [comment]
@shreyamedehal Why not, you can make the necessery corrections and also you can check the social media icons in the expert and contact us pages, it was missed the person who did the PR. Thanks
