### ISSUE TITLE
[FEAT]: Add interactive animation to the homepage

### ISSUE THREAD

**Issue by guptasajal411** [DevOps-Malayalam/DevOps-Community#5]
I noticed that the elements in the website had good animations, but they were missing in this section. 
#### Before:
![](https://i.imgur.com/vkKFz56.gif)
#### After my pull request:
![](https://i.imgur.com/nPmHUXv.gif)

Can you please assign me this issue, it'd be great! :)

**Comment by AlexyPulivelil** [comment]
Cool, really loved it. Feel free to make changes. Thanks

**Comment by guptasajal411** [comment]
Hi, can you add `hacktoberfest-accepted` tag to this issue. Thanks
