### ISSUE TITLE
Adding active navlink and improving footer gap

### ISSUE THREAD

**Issue by developer-diganta** [DevOps-Malayalam/DevOps-Community#51]
There should be an indication for active nav-link.
Before:
![image](https://user-images.githubusercontent.com/65999534/136100313-b6de0aab-1635-4e4c-951f-63d91d38e8aa.png)
After:
![image](https://user-images.githubusercontent.com/65999534/136100383-0f85bb98-264a-4578-83c2-a34006c5a198.png)

Also, there is a gap between the start of footer and the content.
Before:
![image](https://user-images.githubusercontent.com/65999534/136100527-cdb9a8ef-6ae1-4efd-b259-92ba8643153f.png)
After:
![image](https://user-images.githubusercontent.com/65999534/136100568-5fce0b3c-c311-45ac-819c-d8a2872e2f7d.png)

I would like to work on these.

**Comment by AlexyPulivelil** [comment]
@developer-diganta Thanks for the suggestion. You can add necessary changes. Thanks
