### ISSUE TITLE
Making year dynamic

### ISSUE THREAD

**Issue by developer-diganta** [DevOps-Malayalam/DevOps-Community#52]
The year is not dynamically rendered. It has been hard coded.
![image](https://user-images.githubusercontent.com/65999534/136100838-6c706b1e-30f3-482b-aa51-b575555b0c11.png)
I would like to work on this to make the year be dynamically rendered.

**Comment by AlexyPulivelil** [comment]
@developer-diganta Cool, add your edits on that too. Thanks
