### ISSUE TITLE
Background of the footer icons

### ISSUE THREAD

**Issue by JahnaviKashyap19** [DevOps-Malayalam/DevOps-Community#53]
<img src="https://user-images.githubusercontent.com/57027274/136147379-c8c766c0-9f19-485a-80b7-7070ab319d85.png" alt="screenshot" width="600" height="400"/><img src="https://user-images.githubusercontent.com/57027274/136147672-7c588a37-db41-43ac-b2b3-f3737a6fe764.png" alt="screenshot" width="500" height="500"/>

The background of the social icons seems a little off. Can I make it the same as the background color? It will look like this
<img src="https://user-images.githubusercontent.com/57027274/136151588-3be1feb6-0331-4e94-baec-26e0f4d5ac57.png" alt="screenshot" width="400" height="400"/><img src="https://user-images.githubusercontent.com/57027274/136151638-afa9e372-a80b-4cab-be62-ff2772b90956.png" alt="screenshot" width="400" height="400"/>

**Comment by AlexyPulivelil** [comment]
@JahnaviKashyap19 Cool, But will the hover effect on the footer be there after you correct the background.

**Comment by JahnaviKashyap19** [comment]
Yes it will still be there
