### ISSUE TITLE
[BUG]: Hamburger menu icon visible in desktop too

### ISSUE THREAD

**Issue by guptasajal411** [DevOps-Malayalam/DevOps-Community#6]
The hamburger icon for collapsible navbar is visible in the desktop viewport too, when it should be hidden in desktop mode.
#### Screenshot
![image](https://user-images.githubusercontent.com/70312106/135623981-3f760a4d-7008-45fb-9a3e-e670aa607d3c.png)

Please assign me this issue :)

**Comment by AlexyPulivelil** [comment]
Thanks for pointing out the issues. You can make the necessary corrections
