### ISSUE TITLE
Increase security by adding rel=”noopener” on external links ad hide referral information by adding rel=“noreferrer”

### ISSUE THREAD

**Issue by Dkabiswa** [DevOps-Malayalam/DevOps-Community#7]
I realized all external links have no noopeer attribute this provides pages linked from your site and opened in a new tab with partial control over your pages. This might not pose a security threat for now but its a recommended standard to add 

Please assign me this issue :)

**Comment by AlexyPulivelil** [comment]
Thanks for pointing out the issues. You can work on it and make the site more secure.

**Comment by amarealcoder** [comment]
Can I work on this?

**Comment by AlexyPulivelil** [comment]
@Dkabiswa is working on this. There was some merge conflicts in his PR. @amarealcoder you can check for another changes. Thanks

**Comment by amarealcoder** [comment]
Alright thanks for letting me know
