### ISSUE TITLE
[BUG] social media link in the footer are not liked to the community social pages and should open in blank tab

### ISSUE THREAD

**Issue by Dkabiswa** [DevOps-Malayalam/DevOps-Community#9]
![image](https://user-images.githubusercontent.com/26115429/135628092-cfa04331-00aa-4ee1-8053-ccb7817b534c.png)

If the links in social.html are the right social links you can assign me this issue

**Comment by AlexyPulivelil** [comment]
We purposefully removed the social media link. You can check for other changes. Thanks
